### PR TITLE
Fixed issues in Core version 0.7.1

### PR DESCRIPTION
**Pull request by core-wg-admin**

### CODE REVIEW

**Review by pramodkvarma — APPROVED** [review]
Looks good to me.

**Review by abhimail — APPROVED** [review]
Looks good!

**Comment by abhimail** [comment]
Review completed!

**Review by abhimail — APPROVED** [review]

**Comment by abhimail** [comment]
@pramodkvarma requested re-review by mistake! My apologies! Could you please approve so that it can move forward?

**Review by pramodkvarma — APPROVED** [review]
Please go ahead.

**Pull request merged**
